version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: homelab-flip-uptime_app_1
      APP_PORT: 80
    ports:
      - "5760:8080"
    restart: on-failure

  app:
    image: dmytrosmexoff/flip-uptime:latest
    restart: on-failure
    stop_grace_period: 1m
