version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: homelab-minecraft_app_1
      APP_PORT: 5656
    ports:
      - "5772:5770"
    restart: on-failure

  app:
    image: dmytrosmexoff/minecraft-panel:latest
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "5770:5656"
