version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: homelab-minecraft_app_1
      APP_PORT: 5770
    ports:
      - "5770:8080"
    restart: on-failure

  app:
    image: dmytrosmexoff/minecraft-panel:latest
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/data/server:/server"
      - "${APP_DATA_DIR}/data/panel:/data"
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    environment:
      SERVER_DIR: /server
      DATA_DIR: /data
      RCON_PASSWORD: "${RCON_PASSWORD:-mcrcon123}"
      JAVA_OPTS: "${JAVA_OPTS:--Xmx2G -Xms512M}"
