version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: homelab-ragemp_web_1
      APP_PORT: 3000
    ports:
      - "8093:8080"
    restart: on-failure

  game:
    image: dmytrosmexoff/ragemp-game:latest
    container_name: homelab-ragemp_game_1
    restart: on-failure
    stop_grace_period: 30s
    tty: true
    stdin_open: true
    ports:
      - "22005:22005/udp"
      - "22005:22005/tcp"
    volumes:
      - ${APP_DATA_DIR}/data:/server/data
    networks:
      - default

  web:
    image: dmytrosmexoff/ragemp-panel:latest
    container_name: homelab-ragemp_web_1
    restart: on-failure
    depends_on:
      - game
    environment:
      DOCKER_CONTAINER_NAME: homelab-ragemp_game_1
      SERVERS_DIR: /data/servers
      ACTIVE_FILE: /data/active.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/data:/data
    networks:
      - default

networks:
  default:
    driver: bridge
