version: "3.7"
services:
  samp-monitor-api:
    image: ghcr.io/dmytrosmexoff/samp-monitor-api:latest
    restart: on-failure
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - PORT=3000
      - GAME_PORT=7777
      - DATA_DIR=/data
  samp-monitor-web:
    image: ghcr.io/dmytrosmexoff/samp-monitor-web:latest
    restart: on-failure
    expose:
      - "2323"
    environment:
      - API_URL=http://samp-monitor-api:3000
      - PORT=2323
    depends_on:
      - samp-monitor-api
