version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: app
      APP_PORT: 8090
    ports:
      - "4545:8080"
    restart: unless-stopped

  app:
    build: .
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/downloads:/umbrel/umbrel/home/TikTok
      - ${APP_DATA_DIR}/config:/data/config
      - ${APP_DATA_DIR}/media_temp:/data/media_temp
