version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: url-short_app_1
      APP_PORT: 5656

  app:
    build: ./app
    image: homelab/url-short:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
