version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: homelab-samp_web_1
      APP_PORT: 3000
    ports:
      - "8092:8080"
    restart: on-failure

  game:
    image: dmytrosmexoff/samp-game:latest
    container_name: homelab-samp_game_1
    restart: on-failure
    stop_grace_period: 30s
    environment:
      RCON_PASSWORD: "${RCON_PASSWORD:-122344}"
    ports:
      - "7777:7777/udp"
    volumes:
      - ${APP_DATA_DIR}/data:/server/data
    networks:
      - default

  web:
    image: dmytrosmexoff/samp-panel:latest
    container_name: homelab-samp_web_1
    restart: on-failure
    # Сюда мы добавили порт, чтобы зайти напрямую в обход всего
    ports:
      - "3000:3000"
    # МЫ УБРАЛИ SECTION DEPENDS_ON, чтобы разорвать замкнутый круг
    environment:
      SAMP_HOST: homelab-samp_game_1
      SAMP_PORT: "7777"
      SAMP_RCON_PASSWORD: "${RCON_PASSWORD:-122344}"
      DOCKER_CONTAINER_NAME: homelab-samp_game_1
      SERVERS_DIR: /data/servers
      ACTIVE_FILE: /data/active.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/data:/data
    networks:
      - default

networks:
  default:
    driver: bridge
