version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: app
      APP_PORT: 5680
    ports:
      - "5680:8080"
    restart: on-failure
    depends_on:
      - app

  app:
    image: dmytrosmexoff/ragemp-panel:latest
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/data/server:/server"
      - "${APP_DATA_DIR}/data/panel:/data"
    ports:
      - "22005:22005/udp"
      - "22007:22007/tcp"
    environment:
      SERVER_DIR: /server
      DATA_DIR: /data
