version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: homelab-samp-panel_app_1
      APP_PORT: 5656
    ports:
      - "5750:5750"
    restart: on-failure

  app:
    image: dmytrosmexoff/samp-panel:latest
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "7777:7777/udp"
      - "5751:5656"
