version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: flip-uptime
      APP_PORT: 80

  flip-uptime:
    image: dmytrosmexoff/flip-uptime:latest
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
