version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: homelab-tt-dloader_app_1
      APP_PORT: 8091
      
  app:
    image: dmytrosmexoff/tiktok-bot:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/downloads:/data/downloads
      - ${APP_DATA_DIR}/config:/data/config
      - ${APP_DATA_DIR}/media_temp:/data/media_temp
